Feat/time deal service
f-lab-edu/hot-stock pull request #9
Opened 2024-07-23 08:58 UTC by bjcareer

2024-07-23 09:26 UTC, bjcareer commented
#8

2024-07-23 09:28 UTC, bjcareer commented
#8 #6

2024-07-23 22:29 UTC, f-lab-troy requested changes
한 pr의 최대 파일 갯수 5개 이하로 잘라서 보내주시면 좋을 것 같습니다. Logic이 포함되지 않는 파일들은 pr에 포함 안시키셔도 됩니다.

2024-07-24 07:07 UTC, bjcareer commented
> 한 pr의 최대 파일 갯수 5개 이하로 잘라서 보내주시면 좋을 것 같습니다. Logic이 포함되지 않는 파일들은 pr에 포함 안시키셔도 됩니다.

아 넵 처음에 말해주셨는데 commit에 있는 파일 개수를 줄여달라는 말씀으로 착각해버렸슴다. 죄송함다!

리뷰는 이 PR로 부탁드리겠습니다
https://github.com/f-lab-edu/hot-stock/pull/12

2024-07-24 07:07 UTC, closed without merging